// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TalkBot {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("IPhoneViewController")]
	public partial class IPhoneViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_clearButton;
		
		private MonoTouch.UIKit.UITextField __mt_textField;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_openButton;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_saveButton;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_shareButton;
		
		private MonoTouch.UIKit.UIButton __mt_speakButton;
		
		private MonoTouch.iAd.ADBannerView __mt_adView;
		
		private MonoTouch.UIKit.UILabel __mt_placeholderLabel;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("clearButton")]
		private MonoTouch.UIKit.UIButton clearButton {
			get {
				this.__mt_clearButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("clearButton")));
				return this.__mt_clearButton;
			}
			set {
				this.__mt_clearButton = value;
				this.SetNativeField("clearButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("textField")]
		private MonoTouch.UIKit.UITextField textField {
			get {
				this.__mt_textField = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("textField")));
				return this.__mt_textField;
			}
			set {
				this.__mt_textField = value;
				this.SetNativeField("textField", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("openButton")]
		private MonoTouch.UIKit.UIBarButtonItem openButton {
			get {
				this.__mt_openButton = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("openButton")));
				return this.__mt_openButton;
			}
			set {
				this.__mt_openButton = value;
				this.SetNativeField("openButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("saveButton")]
		private MonoTouch.UIKit.UIBarButtonItem saveButton {
			get {
				this.__mt_saveButton = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("saveButton")));
				return this.__mt_saveButton;
			}
			set {
				this.__mt_saveButton = value;
				this.SetNativeField("saveButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("shareButton")]
		private MonoTouch.UIKit.UIBarButtonItem shareButton {
			get {
				this.__mt_shareButton = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("shareButton")));
				return this.__mt_shareButton;
			}
			set {
				this.__mt_shareButton = value;
				this.SetNativeField("shareButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("speakButton")]
		private MonoTouch.UIKit.UIButton speakButton {
			get {
				this.__mt_speakButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("speakButton")));
				return this.__mt_speakButton;
			}
			set {
				this.__mt_speakButton = value;
				this.SetNativeField("speakButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("adView")]
		private MonoTouch.iAd.ADBannerView adView {
			get {
				this.__mt_adView = ((MonoTouch.iAd.ADBannerView)(this.GetNativeField("adView")));
				return this.__mt_adView;
			}
			set {
				this.__mt_adView = value;
				this.SetNativeField("adView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("placeholderLabel")]
		private MonoTouch.UIKit.UILabel placeholderLabel {
			get {
				this.__mt_placeholderLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("placeholderLabel")));
				return this.__mt_placeholderLabel;
			}
			set {
				this.__mt_placeholderLabel = value;
				this.SetNativeField("placeholderLabel", value);
			}
		}
	}
}
